import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/provider";
import { SiteHeader } from "@/components/layouts/site-header";
import { cn } from "@/lib/utils";
import { siteConfig } from "@/config/site-config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
